### ISSUE TITLE
ts-cli无参数时，直接崩缺

### ISSUE THREAD

**Issue by cntpro** [openGemini/openGemini#619]
### Describe the bug（Bug 描述）

直接无参数运行ts-cli，ts-cli直接崩缺
ts-cli 版本
```
openGemini version info:
ts-cli: 1.2.0
git: main 05516f3d0c0d60aa8d72483f9ac4f0e82c5ff1d6
os: linux
arch: amd64

```

### To Reproduce（Bug 复现步骤）

1、克隆源码
```
git clone https://github.com/openGemini/openGemini.git
```
2、编译
```
python3 build.py
```
3、运行ts-cli 必现
```
./ts-cli
```

### Expected behavior（期望结果）

正常运行

### Screenshots（屏幕截图）

![ts-cli](https://github.com/openGemini/openGemini/assets/34875556/e367e43a-0067-4913-8a3b-5b48bc969e0d)

**Comment by xiangyu5632** [comment]
是你静态编译之后的二进制运行panic了是吗？

**Comment by cntpro** [comment]
> 是你静态编译之后的二进制运行panic了是吗？

应该是吧，我又看一下ts-cli是静态的。
有参数时可以正常运行如ts-cli
```
[root@dev k]# ./ts-cli --host 127.0.0.1
openGemini CLI 1.2.0 (rev-revision)
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
> 
```
```
[root@dev k]# ./ts-cli -h
ts-cli is a CLI tool of openGemini.

Usage:
  ts-cli [flags]
  ts-cli [command]
```

**Comment by xuthus5** [comment]
if you do not specify any execution parameters, the command line will trigger the default behavior,connect local opengemini server and test ping/pong.

https://github.com/openGemini/openGemini/blob/61e1436ae371a3a881e9821d2671c9fbdbe19753/app/ts-cli/cmd/interactive.go#L33

when the project references the `net/**` package, it relies on cgo for dynamic linking by default because the network library is implemented differently on different platforms.
according to the error information, the network dependency library during build is incompatible with the current execution environment.
